# Generated by Django 4.2.3 on 2024-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuknox', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='action',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
